### ISSUE TITLE
the connector end after 20 minutes

### ISSUE THREAD

**Issue by maxalone** [Luidog/node-red-contrib-filemaker#20]
sorry for the previous post in the wrong area

I proceeded to update both fms-api-client and node-red-contrib-filemaker, both at the system node-red level and in the app folder

after the first 20 minutes of good functioning the nodes related to node-red-contrib-filemaker stop returning data

the only way to make them work again is to reinstall (manual)

I also tried to install the previous version 1.0.4 because it worked very well but I don't get any difference

we have FMS 18 under windows (on azure)

I'm pretty desperate, this problem is shattering a big project in the company

Thanks for your help

**Comment by Luidog** [comment]
@maxalone sorry to hear you are having trouble. Would you be able to provide me with some more information to troubleshoot this? 

What version of FileMaker are you running?
What version of Node-RED are you running?
Can you attach or send The FileMaker Data API Log file?
Can you send me log output for any flows that are not working?

I am inclined to think there is either something wrong with your FileMaker server or your Node-RED installation I ran into some issues on the preview version of FIleMaker 18 where FileMaker server would not respond to requests. Upgrading the server to the latest (18.0.1.123) seemed to fix it for me. 

You mentioned that now node-red-contrib-filemaker 1.8.4 is no longer working as well for you after reinstalling it. This and the experience I had with the preview version of FileMaker server leads me to think that the issue may not be with the nodes themselves.

**Comment by maxalone** [comment]
What version of FileMaker are you running? -> as I said FMS 18
What version of Node-RED are you running? -> v0.20.3


Can you attach or send The FileMaker Data API Log file? 
Can you send me the log output for any flows that are not working?

**Comment by Luidog** [comment]
@maxalone - There are multiple versions of FileMaker Server 18. I believe the latest is 18.0.1.123. You can compare this to the version in the admin-console to see your specific version. If you happen to be running a version less than 18.0.1.123 that would be useful to know.

It looks like the issue is in fms-api-client. From what I have found right now it looks to be an issue in the start method of the connection model - https://github.com/Luidog/fms-api-client/blob/04afd2113af82aafb828cc8406fc68b7fb13c8fb/src/models/connection.model.js#L155-L176

It is unclear to me at the moment why the authentication request is not responding, but I will issue a patch today to add a timeout to the authentication request. 

You mentioned that this is a significant issue for you. Until we can get a patch for you I recommend you add a flow with an inject node and a FileMaker list node. Set the Inject node for every 14 minutes. This will keep the initial token alive for as long as the flow is running.

**Comment by maxalone** [comment]
sorry for my poor answer, yes we using the 18.0.1.123 rel.
great!I try the methods, if it work I can continue to develop  in the meanwhile
I'm waiting good news from you
thanks!

**Comment by maxalone** [comment]
the inject node repeat the automation at 17.59 and work as expected but at 18.01 when I tried to invoke API from other node app it don't answer already...

**Comment by Luidog** [comment]
@maxalone Thanks for reporting and helping to fix this bug.
