### ISSUE TITLE
Timeout parameter not functioning correctly

### ISSUE THREAD

**Issue by bartdesign** [Luidog/node-red-contrib-filemaker#31]
Hi,

Have made a simple testing flow to run a find query. The query takes rather long. However it keeps stopping me with an timeout exceeded 3000ms. In my server setup my timeout field is empty. Ive tried to change it to 1000 or 50000 but those values don't get used, it keeps giving me the timeout exceeded 3000ms.

Ive included a screenshot.

<img width="476" alt="Schermafbeelding 2020-01-27 om 22 05 09" src="https://user-images.githubusercontent.com/404375/73213817-35439780-4151-11ea-88b0-41fec6e28900.png">
<img width="911" alt="Schermafbeelding 2020-01-27 om 22 04 59" src="https://user-images.githubusercontent.com/404375/73213822-396fb500-4151-11ea-8a9f-ad6933e0ffcd.png">

Ive tried to look at the source but it seems like the timeout is handled fine. Hopefully we can resolve this issue. Thanks!

**Comment by Luidog** [comment]
Hey @bartdesign,

The timeout error you are experiencing is most likely caused by the initial authentication request to the Data API. You can find the underlying logic in [fms-api-client connection model](https://github.com/Luidog/fms-api-client/blob/2a1b43d9f529831cc6bc565f480108ac776786ce/src/models/connection.model.js#L185-L209). 

The authentication timeout is not configurable. The timeout prevents the pending authentication requests from indefinitely block requests made by the client supporting the nodes.  Timeouts on the authentication endpoint usually indicate a Data API misconfiguration or issue communicating with your FileMaker Server. 

I have experienced Data API timeouts due to a lack of server resources. Can you tell me a little bit more about the server and environment you are working in?

**Comment by bartdesign** [comment]
Hi @Luidog,

You are correct. I restarted the filemaker server and the nodes are executing correctly. Thank you for the pointers!

**Comment by jdelacal** [comment]
Hi,
I have serious problems with Timeout error:
"timeout of 3000ms exceeded"
The default time is 3000 ms and from what I have read it cannot be changed.
Currently we have more security systems in companies and they are beginning to put firewalls in series or/and parallel, making these times scarce. Apart from validating against a domain, etc...

Is there a way to increase this value?
